### ISSUE TITLE
SliderServer example?

### ISSUE THREAD

**Issue by JulesArcher** [ghaetinger/notebook-dump#2]
Hello Guilherme,

Listened to your Pluto dashboard talk with great interest, and was able to run your notebook and create simple dashboards of my own.
I am now trying to use PlutoSliderServer to serve a dashboard. It would be great if you could provide a simple working example showing how this can be done!

Thank you!

Jules

**Comment by ghaetinger** [comment]
Hi! Well, there shouldn't be any changes to be done to serve the examples with PlutoSliderServer. It's even simpler because you don't need the Pluto session ID to create the isolated layout URL. I haven't really tested them out, but it should work nonetheless.

One thing that might be cool to do with PlutoSliderServer as a dashboard provider would be to have an automatic redirection instead of a "take me to the dashboard" button. You can do that with:

```javascript
if (!document.URL.includes('isolated')) {
  const cool_url = document.URL + isolated_url_compliment
  window.location = cool_url
}
```

**Comment by ghaetinger** [comment]
@JulesArcher I'm closing this, but feel free to reopen this or contact me at Slack or Zulip.
